### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mfrister** [getsentry/sentry-kubernetes#7]
sentry-kubernetes on our two clusters leaks memory, at least memory usage has only gone up during a few weeks of usage:

<img width="867" alt="screen_shot_2018-04-04_at_15 04 45" src="https://user-images.githubusercontent.com/188986/38350573-269a5e76-38ac-11e8-9485-0b5e9b46969c.png">

We have RBAC enabled and given sentry-kubernetes' service account the ClusterRole `view`.

As a workaround, we've now set the following resource requests/limits for the sentry-kubernetes container:

```yaml
resources:
  requests:
    memory: 75Mi
    cpu: 5m
  limits:
    memory: 100Mi
    cpu: 30m
```

We expect these limits to restart the container every few days.
